version: "3.9"

services:
  backend:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./writers_api:/app
    container_name: backend
    environment:
      - DB_HOST=database
      - DB_NAME=writers_api_db
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=writers_api_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGUSER=postgres
    healthcheck:
      test: [ "CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

